packageExtensions:
  react-intl@5.20.7:
    peerDependencies:
      "@formatjs/ecma402-abstract": "^1.9.6"
      "@formatjs/icu-messageformat-parser": "*"
  "@formatjs/intl@*":
    peerDependencies:
      "@formatjs/icu-messageformat-parser": "*"
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@atls/plugin-essentials.js

yarnPath: .yarn/releases/yarn-3.0.0-rc.5.cjs
