#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

actl precommit
yarn lint yarn typecheck
actl lint actl typecheck
actl lint && actl typecheck
yarn precommit
yarn precommit
yarn precommit
actl lint
actl lint
actl lint
 yarn actl lint
yarn run actl lint
yarn precommit
